Testing for authentication#030
Salim-54/myBrand-Backend pull request #13
Opened 2022-03-17 13:07 UTC by Salim-54

#### What does this PR do?

- Tests authentication API endpoints

#### Description of Task to be completed? 

This is to test authentication API endpoints

#### How should this be manually tested?

- Clone the repo

- checkout to branch ``cr-authentication-api-tests#030``

- Run `npm install` to install modules

- Run `npm  run start` to start the development server

- In your API testing tool (postman recommended) call api `localhost:3000/api/v1/users` to add a todo task

#### Any background context you want to provide?

- N/A

#### What are the relevant Pivotal Tracker/trello stories?

- https://trello.com/c/dsiVJQQv/48-authentication-tests030

#### Screenshots (if appropriate)
- N/A

#### Questions:

- N/A

2022-03-17 17:12 UTC, PrinceNiyonshuti approved these changes
Looks Good

2022-03-17 21:18 UTC, Xldivin approved these changes

2022-03-18 04:59 UTC, PatrickNiyogitare28 requested changes
Remove the comments

2022-03-18 04:59 UTC, PatrickNiyogitare28 commented on src/database/model/user.model.js
> +  // }
Take care of comments

2022-03-18 04:59 UTC, PatrickNiyogitare28 commented on src/database/model/user.model.js
> +  // next();
take care of comments

2022-03-19 20:40 UTC, merged