Feature api-endpoints documentation(SWAGGER)#033
Salim-54/myBrand-Backend pull request #16
Opened 2022-03-17 13:44 UTC by Salim-54

#### What does this PR do?

- Document API endpoints

#### Description of Task to be completed? 

As a user, I should be able to see
- The documentation of all end points

#### How should this be manually tested?

- Clone the repo

- checkout to branch ``ft-api-endpoints-documentation#033``

- Run `npm install` to install modules

- Run `npm  run start` to start the development server

- In your API testing tool (postman recommended) call api `localhost:3000/api/v1/api-docs to 

#### Any background context you want to provide?

- N/A

#### What are the relevant Pivotal Tracker/trello stories?

- https://trello.com/c/Tj3V2a9q/46-swagger-ui-integration033

#### Screenshots (if appropriate)
![Screenshot (286)](https://user-images.githubusercontent.com/81898585/158821853-997eaef4-aaf0-46f8-bdf4-01216bd3299a.png)
![Screenshot (288)](https://user-images.githubusercontent.com/81898585/158821885-1a79d151-03f0-4967-845c-c91ca99ad328.png)

#### Questions:

- N/A

2022-03-17 17:17 UTC, PrinceNiyonshuti approved these changes
Looks good

2022-03-17 17:18 UTC, PrinceNiyonshuti approved these changes
nicely done

2022-03-17 21:21 UTC, Xldivin approved these changes

2022-03-18 05:06 UTC, PatrickNiyogitare28 requested changes

2022-03-18 05:06 UTC, PatrickNiyogitare28 commented on .env
> +CLOUDINARY_API_SECRET=7g0ugXbZjMVdZehREBIyDQGmCS0
Put `.env` file in `.gitignore` , we don't need push to github

2022-03-18 05:06 UTC, PatrickNiyogitare28 commented on .nyc_output/processinfo/9bb5eb35-3b76-4e57-82a4-3c490488c524.json
> +{"parent":null,"pid":7972,"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\salim\\3D Objects\\backend\\node_modules\\mocha\\bin\\mocha","--require","@babel/register","./src/tests/","--recurs
Put `.`nyc_output` under `.gitignore` no need of pushing it to GitHub as well

2022-03-18 05:06 UTC, PatrickNiyogitare28 commented on src/database/model/user.model.js
Remove the commented source codes for best code quality

2022-03-19 20:41 UTC, merged